version: '3.8'
networks:
  app-tier:
    driver: bridge
services:
  nginx:
    networks:
      - app-tier
    build:
      context: ./nginx
    container_name: nginx
    volumes:
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    depends_on:
      - jjincafe_server
    restart: 'unless-stopped'
    ports:
      - '80:80'
      - '443:443'
    expose:
      - '80'
      - '443'
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot: # certbot 서비스 추가
    image: certbot/certbot
    container_name: certbot_service
    volumes:
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
